services:
  - type: web
    name: capture-logs
    env: node
    region: oregon
    envVars:
      - key: NEXTDNS_PROFILE
        value: "85d564"
      - key: NEXTDNS_API_KEY
        value: "f31f2871d328a52a45fefadc09a1c67d0dd5d53d"
      - key: GIT_REPO_URL
        value: "https://github.com/diogo0587/lognextdns"
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y jq curl git
    startCommand: |
      #!/bin/bash
      set -e

      # ... (código anterior permanece o mesmo)

      echo "Initializing git repository..."
      git config --global user.email "diogos0587@gmail.com"
      git config --global user.name "Diogo0587"
      git init
      
      echo "Adding files to git..."
      git add logs/
      
      echo "Committing changes..."
      git commit -m "Add daily log files and URLs for $(date +'%Y-%m-%d')"
      
      echo "Pushing to remote repository..."
      if ! git push -f $GIT_REPO_URL main; then
        echo "Failed to push to remote repository. Exiting."
        exit 1
      fi
      
      echo "Script completed successfully."
