services:
  - type: web
    name: capture-logs
    env: python
    region: oregon
    envVars:
      - key: NEXTDNS_PROFILE
        value: "85d564"
      - key: NEXTDNS_API_KEY
        value: "f31f2871d328a52a45fefadc09a1c67d0dd5d53d"
    buildCommand: pip install requests pyyaml
    startCommand: python generate_logs.py && python -m http.server 8080
