services:
  - type: web
    name: capture-logs
    env: node
    region: oregon
    envVars:
      - key: NEXTDNS_PROFILE
        value: "85d564"
      - key: NEXTDNS_API_KEY
        value: "f31f2871d328a52a45fefadc09a1c67d0dd5d53d"
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y curl jq
    startCommand: |
      mkdir -p logs && \
      curl -s -X GET "https://api.nextdns.io/profiles/$NEXTDNS_PROFILE/logs?raw=1" -H "X-Api-Key: $NEXTDNS_API_KEY" -o logs/daily_log$(date +'%Y-%m-%d').json && \
      jq -r '.data[].url' logs/daily_log$(date +'%Y-%m-%d').json > logs/urls_$(date +'%Y-%m-%d').txt && \
      jq -c '.data[]' logs/daily_log$(date +'%Y-%m-%d').json | while read -r log; do \
        device=$(echo "$log" | jq -r '.device') && \
        mkdir -p logs/$device && \
        echo "$log" | jq '.' > logs/$device/daily_log_$(date +'%Y-%m-%d').json \
      done && \
      git config --global user.name "${{ github.actor }}" && \
      git config --global user.email "${{ github.actor }}@users.noreply.github.com" && \
      git checkout main && \
      git add logs/ && \
      git commit -m "Add daily log files and URLs for $(date +'%Y-%m-%d')" && \
      git push origin main
