version: 2.1

jobs:
  capture-logs:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install curl and jq
          command: |
            sudo apt-get update
            sudo apt-get install -y curl jq
      - run:
          name: Capture Logs and Separate by Device
          command: |
            mkdir -p logs
            curl -s -X GET "https://api.nextdns.io/profiles/85d564/logs" -H "X-Api-Key: f31f2871d328a52a45fefadc09a1c67d0dd5d53d" -o logs/daily_log.json
            # Extrair URLs do arquivo JSON
            jq -r '.data[].url' logs/daily_log.json > logs/urls_$(date +'%Y-%m-%d').txt
            # Separar logs por dispositivo e salvar em arquivos específicos
            jq -c '.data[]' logs/daily_log.json | while read -r log; do
              device=$(echo "$log" | jq -r '.device')
              mkdir -p logs/$device
              echo "$log" | jq '.' > logs/$device/daily_log_$(date +'%Y-%m-%d').json
            done
      - run:
          name: Set Git User
          command: |
            git config --global user.name "${CIRCLE_USERNAME}"
            git config --global user.email "${CIRCLE_USERNAME}@users.noreply.github.com"
      - run:
          name: Add and Commit Logs
          command: |
            git checkout main  # Garanta que está na branch correta
            git add logs/
            git commit -m "Add daily log files and URLs for $(date +'%Y-%m-%d')"
            git push origin main  # Garanta que está empurrando para a branch correta

workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"  # Executa todo dia à meia-noite (UTC)
    jobs:
      - capture-logs