# Ação Diária para Salvar Logs do NextDNS

name: Salvar Logs do NextDNS

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  save-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Obter logs do NextDNS
        run: |
          X-Api-Key="f31f2871d328a52a45fefadc09a1c67d0dd5d53d"
          PROFILE_ID="85d564"
          LOG_FILE="nextdns_logs_$(date +'%Y-%m-%d').json"

          curl -s -H "Authorization: Bearer $API_KEY" "https://api.nextdns.io/v1/logs/$PROFILE_ID" | jq '.' > $LOG_FILE

      - name: Enviar logs para o repositório
        run: |
          git config --local user.email "diogos0587@gmail.com"
          git config --local user.name "diogos0587"
          git add nextdns_logs_*.json
          git commit -m "Atualização diária dos logs do NextDNS"
          git pull
          git push
