# Ação Diária para Salvar Logs do NextDNS

name: Salvar Logs do NextDNS

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  save-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Obter logs do NextDNS
        env:
          X_API_KEY: ${{ secrets.NEXTDNS_API_KEY }}
          PROFILE_ID: "85d564"
          LOG_FILE: "nextdns_logs_$(date +'%Y-%m-%d').json"
        run: |
          curl -s -H "X-Api-Key: $X_API_KEY" "https://api.nextdns.io/profiles/$PROFILE_ID/logs" | jq '.' > $LOG_FILE

      - name: Enviar logs para o repositório
        run: |
          git config --global user.name "Seu Nome"
          git config --global user.email "seuemail@exemplo.com"
          git add nextdns_logs_*.json
          git commit -m "Atualização diária dos logs do NextDNS"
          git pull
          git push
