name: Download NextDNS Logs

on:
  schedule:
    - cron: '0 0 * * *'  # Diariamente, às 00:00
  workflow_dispatch:

jobs:
  download-logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download logs
        run: |
          curl -X GET \
          -H "X-Api-Key: Bearer ${{ secrets.NEXTDNS_TOKEN }}" \
          https://api.nextdns.io/profiles/85d564/logs \
          -o nextdns-logs.json
      - name: Commit and push
        run: |
          git config user.name 'Diogo0587'
          git config user.email 'diogos0587@gmail.com'
          git add nextdns-logs.json
          git commit -m "Adicionando logs do NextDNS do dia $(date +%Y-%m-%d)"
          git push
