# .github/workflows/site-painel.yml
name: Build & Deploy Hugo site (subpasta painel)

# Gatilhos
on:
  push:
    branches: [gh-pages]        # só roda em commits nessa branch
  workflow_dispatch:            # permite disparar manualmente

# Permissões mínimas p/ publicar no Pages
permissions:
  contents: read
  pages: write
  id-token: write

# --------------------------------------
jobs:
  build:
    runs-on: ubuntu-22.04
    # Todas as etapas executam dentro de painel/
    defaults:
      run:
        working-directory: ./painel

    steps:
      # 1. Checkout do próprio commit em gh-pages
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages          # garante branch correta
          fetch-depth: 1
          submodules: false
      - name: Create painel directory
        run: mkdir -p painel
      # 2. Instala Hugo extended
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      # 3. Instala Python (para coletar logs)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4. Baixa logs NextDNS e cria posts
      - name: Fetch NextDNS logs & generate content
        env:
          NEXTDNS_API_KEY: ${{ secrets.NEXTDNS_API_KEY }}
          NEXTDNS_PROFILE_ID: ${{ secrets.NEXTDNS_PROFILE_ID }}
        run: |
          mkdir -p content/posts
          python <<'PY'
          import os, requests, pathlib, textwrap
          from datetime import datetime

          url = f"https://api.nextdns.io/profiles/{os.getenv('NEXTDNS_PROFILE_ID')}/logs"
          r   = requests.get(url,
                             headers={"X-Api-Key": os.getenv("NEXTDNS_API_KEY")},
                             params={"limit":250,"from":"-1h","raw":"1"})
          r.raise_for_status()
          logs = r.json().get("data", [])
          if not logs:
              print("Nenhum log encontrado."); exit(0)

          pathlib.Path("content").mkdir(exist_ok=True)
          with open("content/_index.md","w",encoding="utf-8") as f:
              f.write(textwrap.dedent("""\
              ---
              title: "NextDNS Logs Dashboard"
              ---
              Bem-vindo ao Dashboard de Logs do NextDNS.
              """))

          for i, log in enumerate(logs[:30], 1):
              front = textwrap.dedent(f"""\
              ---
              title: "Log {i}"
              date: "{datetime.now().isoformat()}"
              domain: "{log.get('domain','N/A')}"
              status: "{log.get('status','N/A')}"
              timestamp: "{log.get('timestamp','N/A')}"
              ---
              """)
              with open(f"content/posts/log-{i}.md","w",encoding="utf-8") as fp:
                  fp.write(front)
          PY

      # 5. Instala tema BeautifulHugo (clone simples)
      - name: Install BeautifulHugo theme
        run: |
          mkdir -p themes
          [ -d themes/beautifulhugo ] || \
          git clone --depth 1 https://github.com/halogenica/beautifulhugo.git themes/beautifulhugo

      # 6. Escreve config.toml
      - name: Write config.toml
        run: |
          cat > config.toml <<'CFG'
          baseURL = "https://diogo0587.github.io/lognextdns/"
          canonifyURLs = true
          languageCode = "pt-br"
          title = "NextDNS Logs"
          theme = "beautifulhugo"
          [pagination]
            pagerSize = 10
          CFG

      # 7. Build estático na pasta painel/public
      - name: Build Hugo site
        run: hugo --minify --destination public

      # 8. Configura Pages e faz upload do artefato
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./painel/public

  # ------------------------------------
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
