name: Build Hugo Site with NextDNS Logs and Deploy to Pages

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Verificar instalação do Hugo
        run: hugo version

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências do Python
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Buscar logs do NextDNS e gerar conteúdo Hugo
        env:
          NEXTDNS_API_KEY: ${{ secrets.NEXTDNS_API_KEY }}
          NEXTDNS_PROFILE_ID: ${{ secrets.NEXTDNS_PROFILE_ID }}
        run: |
          mkdir -p content/posts
          python3 scripts/generate_logs.py

      - name: Configurar Hugo
        run: |
          if [ ! -f "config.toml" ]; then
            hugo new site . --force
          fi
          if [ ! -d "themes/ananke" ]; then
            git clone https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke
          fi
          cat <<EOT > config.toml
          theme = "ananke"
          baseURL = "https://${GITHUB_REPOSITORY_OWNER}.github.io"
          paginate = 10
          EOT

      - name: Build Hugo site
        run: hugo --minify

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './public'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

