name: Capture Logs
on:
  schedule:
    - cron: '0 0 * * *'  # Executa todo dia à meia-noite (UTC)
  workflow_dispatch:

jobs:
  capture-logs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Install curl and jq
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Capture Logs and Generate HTML
      run: |
        echo "Fetching logs from NextDNS"
        curl -s -X GET "https://api.nextdns.io/profiles/85d564/logs?raw=1" -H "X-Api-Key: f31f2871d328a52a45fefadc09a1c67d0dd5d53d" -o daily_log$(date +'%Y-%m-%d').json
        echo "Logs fetched: $(cat daily_log$(date +'%Y-%m-%d').json)"
        echo "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>NextDNS Logs</title><style>body{font-family: Arial, sans-serif;}table{width: 100%; border-collapse: collapse;}th,td{text-align: left; padding: 8px;}th{background-color: #f2f2f2;}tr:nth-child(even){background-color: #f9f9f9;}tr:hover{background-color: #f1f1f1;}h1{text-align: center;}</style></head><body><h1>NextDNS Logs for $(date +'%Y-%m-%d')</h1><table border=\"1\"><tr><th>Timestamp</th><th>Domain</th><th>Type</th><th>Status</th><th>Client IP</th></tr>" > index.html
        jq -c '.data[]' daily_log$(date +'%Y-%m-%d').json | while read -r log; do
          timestamp=$(echo "$log" | jq -r '.timestamp')
          domain=$(echo "$log" | jq -r '.domain')
          type=$(echo "$log" | jq -r '.type')
          status=$(echo "$log" | jq -r '.status')
          client_ip=$(echo "$log" | jq -r '.clientIp')
          echo "<tr><td>$timestamp</td><td><a href=\"http://$domain\">$domain</a></td><td>$type</td><td>$status</td><td>$client_ip</td></tr>" >> index.html
        done
        echo "</table></body></html>" >> index.html

    - name: Set Git User
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Add and Commit Logs and HTML
      run: |
        git add index.html daily_log$(date +'%Y-%m-%d').json
        git commit -m "Update logs and HTML for $(date +'%Y-%m-%d')"
        git push
