name: NextDNS Logs Dashboard

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  workflow_dispatch:  # Permite execução manual

env:
  NEXTDNS_API_KEY: f31f2871d328a52a45fefadc09a1c67d0dd5d53d
  NEXTDNS_PROFILE_ID: 85d564

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3

    - name: Create Kubernetes cluster
      run: |
        kubectl create deployment nextdns-dashboard --image=nginx:alpine
        kubectl expose deployment nextdns-dashboard --type=LoadBalancer --port=80

    - name: Fetch NextDNS logs
      run: |
        curl -X GET "https://api.nextdns.io/profiles/${{ env.NEXTDNS_PROFILE_ID }}/logs" \
             -H "X-Api-Key:${{ env.NEXTDNS_API_KEY }}" > logs.json

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Create Hugo site
      run: |
        hugo new site dashboard
        cd dashboard
        git init
        git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke
        echo "theme = 'ananke'" >> config.toml

    - name: Generate dashboard content
      run: |
        python3 - <<EOF
        import json
        import os
        from datetime import datetime

        with open('logs.json', 'r') as f:
            logs = json.load(f)

        os.makedirs('dashboard/content/posts', exist_ok=True)

        for i, log in enumerate(logs['data']):
            with open(f'dashboard/content/posts/log-{i+1}.md', 'w') as f:
                f.write(f"""
        ---
        title: "Log Entry {i+1}"
        date: {datetime.now().isoformat()}
        ---

        Domain: {log.get('domain', 'N/A')}
        Status: {log.get('status', 'N/A')}
        Timestamp: {log.get('timestamp', 'N/A')}
        """)

        with open('dashboard/content/_index.md', 'w') as f:
            f.write("""
        ---
        title: "NextDNS Logs Dashboard"
        ---

        Welcome to the NextDNS Logs Dashboard. Below are the latest log entries.
        """)
        EOF

    - name: Build Hugo site
      run: |
        cd dashboard
        hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dashboard/public
