name: Run NextDNS Log Analysis

on:
  schedule:
    - cron: "0 * * * *"  # Executa a cada hora
  workflow_dispatch:  # Permite disparo manual do workflow

jobs:
  collect-and-analyze-logs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Atualizado para v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
        import: logging


# Use logger.info(), logger.error(), etc. para registrar mensagens
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Collect logs
      run: |
        python scripts/collect_logs.py

    - name: Analyze logs
      run: |
        python scripts/analyze_logs.py

    - name: Commit and Push Analysis
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git add logs/nextdns_logs_analysis.json
        git commit -m "Atualização da análise de logs do NextDNS: $(date)"
        git push origin main
