name: Capture Logs
on:
  schedule:
    - cron: '0 0 * * *'  # Executa todo dia à meia-noite (UTC)
  workflow_dispatch:

jobs:
  capture-logs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install curl and jq
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Capture Logs and Process Data
      run: |
        mkdir -p logs
        curl -s -X GET "https://api.nextdns.io/profiles/85d564/logs?raw=1" -H "X-Api-Key: f31f2871d328a52a45fefadc09a1c67d0dd5d53d" -o logs/daily_log$(date +'%Y-%m-%d').json
        
        # Processar o arquivo JSON e preparar dados para o Notion
        jq -c '.data[]' logs/daily_log$(date +'%Y-%m-%d').json | while read -r log; do
          url=$(echo "$log" | jq -r '.url')
          device=$(echo "$log" | jq -r '.device')
          timestamp=$(echo "$log" | jq -r '.timestamp')
          status=$(echo "$log" | jq -r '.status')
          
          # Adicionar entrada ao banco de dados do Notion
          curl -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer ntn_G89151370362xFd0vbIxGyRniZndeBtI9z3HgYgt7Z6fvY" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            -d '{
              "parent": { "database_id": "14c21362320c81e78569fe440f1ae157" },
              "properties": {
                "URL": {
                  "title": [{ "text": { "content": "'"$url"'" } }]
                },
                "Device": {
                  "rich_text": [{ "text": { "content": "'"$device"'" } }]
                },
                "Timestamp": {
                  "date": { "start": "'"$timestamp"'" }
                },
                "Status": {
                  "select": { "name": "'"$status"'" }
                }
              }
            }'
        done

    - name: Set Git User
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Pull Latest Changes
      run: |
        git pull origin main

    - name: Add and Commit Logs
      run: |
        git checkout main
        if [[ `git status --porcelain` ]]; then
          git add logs/
          git commit -m "Add daily log files for $(date +'%Y-%m-%d')"
          git push origin main
        else
          echo "No changes to commit"
        fi
