name: Atualizar Logs NextDNS

on:
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas
  push:
    branches: [ main ]  # Executa em cada push para a branch main
  workflow_dispatch:  # Permite execução manual

jobs:
  update-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Verificar diretório e conteúdo
        run: |
          pwd
          ls -la

      - name: Criar package.json se não existir
        run: |
          if [ ! -f package.json ]; then
            npm init -y
            npm install @vercel/analytics
          fi

      - name: Instalar dependências
        run: npm install

      - name: Obter logs do NextDNS e gerar página HTML
        env:
          NEXTDNS_PROFILE: ${{ secrets.NEXTDNS_PROFILE }}
          NEXTDNS_API_KEY: ${{ secrets.NEXTDNS_API_KEY }}
        run: |
          response=$(curl -s -H "X-Api-Key: $NEXTDNS_API_KEY" "https://api.nextdns.io/profiles/$NEXTDNS_PROFILE/logs?raw=1")
          
          cat << EOF > index.html
          <!DOCTYPE html>
          <html lang="pt-BR">
          <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>NextDNS Logs</title>
              <script type="module">
                import { inject } from '@vercel/analytics';
                inject();
              </script>
          </head>
          <body>
              <h1>NextDNS Logs</h1>
              <pre id="logs"></pre>
              <script>
                  document.getElementById('logs').textContent = JSON.stringify($response, null, 2);
              </script>
          </body>
          </html>
          EOF

      - name: Configurar Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit e push das alterações
        run: |
          git add index.html
          git commit -m "Atualizar logs do NextDNS para $(date +'%Y-%m-%d')"
          git push

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
