name: Atualizar Logs NextDNS

on:
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas
  workflow_dispatch:  # Permite execução manual

jobs:
  update-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          pip install requests psycopg2-binary

      - name: Obter e processar logs do NextDNS
        run: |
          python - <<EOF
          import requests
          import json
          import psycopg2
          from datetime import datetime

          # Obter logs do NextDNS
          url = "https://api.nextdns.io/profiles/85d564/logs"
          headers = {"X-Api-Key": "f31f2871d328a52a45fefadc09a1c67d0dd5d53d"}
          response = requests.get(url, headers=headers)
          logs = response.json()["data"]

          # Conectar ao PostgreSQL
          conn = psycopg2.connect("postgres://default:0jBoHRKeQkP8@ep-blue-sky-a4giv1wk.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require")
          cur = conn.cursor()

          # Criar tabela se não existir
          cur.execute("""
          CREATE TABLE IF NOT EXISTS nextdns_logs (
              id SERIAL PRIMARY KEY,
              timestamp TIMESTAMP,
              domain VARCHAR(255),
              root VARCHAR(255),
              tracker VARCHAR(255),
              encrypted BOOLEAN,
              protocol VARCHAR(50),
              client_ip VARCHAR(50),
              status VARCHAR(50),
              reasons JSONB
          )
          """)

          # Inserir logs no banco de dados
          for log in logs:
              cur.execute("""
              INSERT INTO nextdns_logs (timestamp, domain, root, tracker, encrypted, protocol, client_ip, status, reasons)
              VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
              """, (
                  datetime.fromisoformat(log['timestamp'].replace('Z', '+00:00')),
                  log['domain'],
                  log['root'],
                  log.get('tracker', ''),
                  log['encrypted'],
                  log['protocol'],
                  log['clientIp'],
                  log['status'],
                  json.dumps(log['reasons'])
              ))

          conn.commit()
          cur.close()
          conn.close()

          print(f"Processados {len(logs)} registros de log.")
          EOF

      - name: Gerar relatório HTML
        run: |
          python - <<EOF
          import psycopg2
          from datetime import datetime

          conn = psycopg2.connect("postgres://default:0jBoHRKeQkP8@ep-blue-sky-a4giv1wk.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require")
          cur = conn.cursor()

          cur.execute("SELECT COUNT(*) FROM nextdns_logs")
          total_logs = cur.fetchone()[0]

          cur.execute("SELECT domain, COUNT(*) FROM nextdns_logs GROUP BY domain ORDER BY COUNT(*) DESC LIMIT 10")
          top_domains = cur.fetchall()

          cur.execute("SELECT tracker, COUNT(*) FROM nextdns_logs WHERE tracker != '' GROUP BY tracker ORDER BY COUNT(*) DESC LIMIT 10")
          top_trackers = cur.fetchall()

          cur.close()
          conn.close()

          html_content = f"""
          <!DOCTYPE html>
          <html lang="pt-BR">
          <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Relatório de Logs NextDNS</title>
          </head>
          <body>
              <h1>Relatório de Logs NextDNS</h1>
              <p>Total de logs: {total_logs}</p>
              <h2>Top 10 Domínios</h2>
              <ul>
                  {"".join(f"<li>{domain}: {count}</li>" for domain, count in top_domains)}
              </ul>
              <h2>Top 10 Trackers</h2>
              <ul>
                  {"".join(f"<li>{tracker}: {count}</li>" for tracker, count in top_trackers)}
              </ul>
              <p>Gerado em: {datetime.now().isoformat()}</p>
          </body>
          </html>
          """

          with open('nextdns_report.html', 'w') as f:
              f.write(html_content)
          EOF

      - name: Commit e push das alterações
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add nextdns_report.html
          git commit -m "Atualizar relatório de logs NextDNS"
          git push

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
