name: Deploy Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Baixa Znai JAR oficial da release (substitua a versão se necessário)
      - name: Download Znai JAR
        run: curl -L -o znai.jar https://github.com/znaidev/znai/releases/download/v1.45/znai-1.45.jar

      # Gera a documentação usando Java (não necessita unzip)
      - name: Build Znai Documentation
        run: java -jar znai.jar --output-dir znai-docs/target/znai

      # Opcional para debug: lista o conteúdo gerado no diretório de saída
      - name: List build output (debug)
        run: ls -lh znai-docs/target/znai

      # Publica a documentação no branch gh-pages usando a action recomendada
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./znai-docs/target/znai
          
